### ISSUE TITLE
Relocatable packages

### ISSUE THREAD

**Issue by saadrahim** [ROCm/rocm-cmake#37]
https://github.com/RadeonOpenCompute/rocm-cmake/blob/9205ef475d23eb9a8c3e5990cc76a98378a21a1e/share/rocm/cmake/ROCMCreatePackage.cmake#L30

CPackRPM:Warning: CPACK_SET_DESTDIR is set (=ON) while requesting a relocatable package (CPACK_RPM_PACKAGE_RELOCATABLE is set): this is not supported, the package won't be relocatable.

Can we look at supporting relocatable packages by default? Do we need this value set?

**Comment by nartmada** [comment]
Hi @saadrahim, is there any further work required for this ticket?  Can I close it?  Thanks.

**Comment by saadrahim** [comment]
This doesn't need to be tracked here.
