### ISSUE TITLE
find_package (ROCM is confusing

### ISSUE THREAD

**Issue by saadrahim** [ROCm/rocm-cmake#49]
Invoking 
find_package( ROCM 0.5 CONFIG QUIET PATHS ${ROCM_PATH} /opt/rocm )
to include rocm-cmake is confusing. 

We should consider changing the name to ROCM-CMAKE.

**Comment by lawruble13** [comment]
@pfultz2 Can you weigh in on this? Using the name `ROCM` is confusing, especially with the version numbers which don't match the ROCm version number, and we have the opportunity to make a breaking change with ROCm 5.0.

**Comment by nartmada** [comment]
Hi @saadrahim, is there any further work required for this ticket?  Can I close it?  Thanks.

**Comment by cgmb** [comment]
It is `find_package(ROCmCMakeBuildTools)` in ROCm 6.1 and later, although `find_package(ROCM)` remains available for backwards-compatibility.
